### ISSUE TITLE
Extension fails to load (Linux OS)

### ISSUE THREAD

**Issue by Cutuchiqueno** [DeltaXML/vscode-xslt-tokenizer#27]
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.52-1-MANJARO

The extension can not be loaded and throws the following error in the logs:

```
[2020-08-26 18:50:03.712] [exthost] [error] Activating extension deltaxml.xslt-xpath failed due to an error:
[2020-08-26 18:50:03.717] [exthost] [error] Error: Cannot find module './xsltSchema'
Require stack:
- /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/languageConfigurations.js
- /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/extension.js
- /opt/visual-studio-code/resources/app/out/vs/loader.js
- /opt/visual-studio-code/resources/app/out/bootstrap-amd.js
- /opt/visual-studio-code/resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:764:15)
    at Module._load (internal/modules/cjs/loader.js:669:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
    at Function.i._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
    at Function.n._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
    at Module.require (internal/modules/cjs/loader.js:822:19)
    at n (/opt/visual-studio-code/resources/app/out/vs/loader.js:16:135)
    at Object.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/languageConfigurations.js:5:22)
    at Module.o._compile (/opt/visual-studio-code/resources/app/out/vs/loader.js:16:360)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:939:10)
    at Module.load (internal/modules/cjs/loader.js:782:32)
    at Module._load (internal/modules/cjs/loader.js:695:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
    at Function.i._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
    at Function.n._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
    at Module.require (internal/modules/cjs/loader.js:822:19)
    at n (/opt/visual-studio-code/resources/app/out/vs/loader.js:16:135)
    at Object.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/extension.js:26:34)
    at Module.o._compile (/opt/visual-studio-code/resources/app/out/vs/loader.js:16:360)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:939:10)
    at Module.load (internal/modules/cjs/loader.js:782:32)
    at Module._load (internal/modules/cjs/loader.js:695:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Function.t._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1005:775)
    at Function.i._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:975:661)
    at Function.n._load (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:971:844)
    at Module.require (internal/modules/cjs/loader.js:822:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Function.s [as __$__nodeRequire] (/opt/visual-studio-code/resources/app/out/vs/loader.js:33:604)
    at h._loadCommonJSModule (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:976:874)
    at h._doActivateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:393)
    at h._activateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:453)
    at Object.actualActivateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:230)
    at h._activateExtension (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:603)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:281
    at Array.map (<anonymous>)
    at h._activateExtensions (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:612:269)
    at h.activateByEvent (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:609:745)
    at h._activateByEvent (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:873:122)
    at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:882:55
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by Cutuchiqueno** [comment]
I figured out that the issue might relate to a file `xsltSchema.js` that in my install of the extension (~/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/) actually is called `xsltschema.hs`. Thus, it has a different case and Linux obviously is case-sensitive for file path. I do not know if this is actually the issue but after renaming thins file I get a different error message than before. This time it is:

```
[2020-08-26 19:10:30.511] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.523] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-26 19:10:30.523] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.523] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-26 19:10:30.523] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.524] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-26 19:10:30.524] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.524] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-26 19:10:30.594] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.594] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
[2020-08-26 19:10:30.645] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2020-08-26 19:10:30.645] [exthost] [info] ExtensionService#loadCommonJSModule file:///opt/visual-studio-code/resources/app/extensions/github/dist/extension.js
[2020-08-26 19:10:30.656] [exthost] [error] [deltaxml.xslt-xpath] provider FAILED
[2020-08-26 19:10:30.656] [exthost] [error] Error: Illegal argument: character must be non-negative
    at Object.t.illegalArgument (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:10:662)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:444:424)
    at new v (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:276)
    at Function.getTextForToken (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:347:24)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:1022:63
    at Array.forEach (<anonymous>)
    at Function.XsltTokenDiagnostics.calculateDiagnostics (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltTokenDiagnostics.js:962:15)
    at /home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:92:79
    at new Promise (<anonymous>)
    at XsltSymbolProvider.<anonymous> (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:46:20)
    at Generator.next (<anonymous>)
    at fulfilled (/home/niels/.vscode/extensions/deltaxml.xslt-xpath-0.1.7/out/xsltSymbolProvider.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

I think I leave it like that for now, not exactly knowing if I went into a completely wrong direction or not. Probably you have clearer idea about this.

**Comment by pgfearo** [comment]
Thank you for reporting both issues:
1. Extension activation error due to incorrect module name: xsltschema.js
2. getTextForToken function error: Illegal argument: character must be non-negative

V0.1.8 of this extension has now been published which fixes issue (1). 
Regarding issue (2), I've added a check inside the function preventing a negative character number. The change means that if the character number negative a more helpful error should be logged, but the code should still run.

There is still an issue however for (2), the tokenizer should not produce negative character numbers so there is still a bug. Does this error occur when any XML/XSLT file is opened? If it's just for a specific file, could you please attach a file that reproduces the problem.

**Comment by Cutuchiqueno** [comment]
thx. for the quick feedback. I confirm that since v0.1.8 (1) is solved.

(2) now only happens when I create a new *empty* stylesheet. Stylesheets that have content already open and load the extension just fine.

(I know this does not belong in an issue report but still I wanted to say that I am so happy that this extension now exists, so thank you for the work!)

**Comment by pgfearo** [comment]
Ok, thanks for that info on (2) affecting just new empty stylesheets, I should be able to uncover the problem here.

Also, your encouraging comments are much appreciated.
